#!/usr/bin/env python3
"""
NYT Crossword Fetcher
Fetches today's (or any date's) NYT crossword puzzle and outputs
Python Entry initializer code ready to paste into your solver.

Usage:
    python nyt_crossword_fetch.py --cookie "YOUR_NYT-S_COOKIE"
    python nyt_crossword_fetch.py --cookie "YOUR_NYT-S_COOKIE" --date 2026-03-10
    python nyt_crossword_fetch.py --cookie "YOUR_NYT-S_COOKIE" --date 2026-03-10 --output puzzle.py

How to get your NYT-S cookie:
    1. Open browser DevTools (F12) while on the NYT crossword page
    2. Go to the Network tab and click any .json request
    3. In the Request Headers, find the Cookie field
    4. Copy the value of NYT-S=... (just the value, not "NYT-S=")
"""

import argparse
import json
import sys
from datetime import date
from typing import Any
import requests

# Type aliases
PuzzleData = dict[str, Any]
CellData = dict[str, Any]
ClueEntry = tuple[str, str, tuple[int, int], int]  # (clue_text, answer, (row, col), length)
EntriesDict = dict[str, ClueEntry]


def fetch_puzzle(date_str: str, nyt_s_cookie: str) -> PuzzleData:
    """Fetch the puzzle JSON from the NYT API."""
    url = f"https://www.nytimes.com/svc/crosswords/v6/puzzle/daily/{date_str}.json"
    response = requests.get(
        url,
        headers={
            "Cookie": f"NYT-S={nyt_s_cookie};",
            "Accept": "application/json",
        }
    )
    if response.status_code == 401:
        print("Error: Authentication failed. Check your NYT-S cookie.", file=sys.stderr)
        sys.exit(1)
    if response.status_code != 200:
        print(f"Error: HTTP {response.status_code} fetching puzzle.", file=sys.stderr)
        sys.exit(1)
    return response.json()  # type: ignore[no-any-return]


def parse_puzzle(data: PuzzleData) -> EntriesDict:
    """
    Parse NYT puzzle JSON into a dict of Entry constructor args.

    The v6 API body[0] contains:
      - cells: flat list of cell dicts, left-to-right, top-to-bottom
          Each cell has: 'answer' (letter or '.'), 'clues' ([across_id, down_id] ints or absent)
      - clues: {'across': [...], 'down': [...]}
          Each clue: {'cells': [cell_indices], 'clueNum': int, 'text': {'plain': str}}
      - dimensions: {'width': int, 'height': int}

    Returns dict mapping clue key (e.g. "1A") -> (clue_text, answer, (row, col), length)
    """
    body: dict[str, Any] = data["body"][0]
    cells: list[CellData] = body["cells"]
    clue_data: dict[str, list[dict[str, Any]]] = body["clues"]
    width: int = body["dimensions"]["width"]

    entries: EntriesDict = {}

    for direction, suffix in [("across", "A"), ("down", "D")]:
        for clue in clue_data[direction]:
            clue_num: int = clue["clueNum"]
            clue_text_raw: list[dict[str, Any]] | dict[str, Any] = clue["text"]
            clue_text: str = clue_text_raw[0]["plain"] if isinstance(clue_text_raw, list) else clue_text_raw["plain"]
            cell_indices: list[int] = clue["cells"]

            # Derive answer from cell letters
            answer: str = "".join(
                cells[i].get("answer", "?") for i in cell_indices
            )
            # Replace block cells just in case
            answer = answer.replace(".", "?")

            length: int = len(cell_indices)

            # Start position: first cell index -> (row, col)
            first_idx: int = cell_indices[0]
            row: int = first_idx // width
            col: int = first_idx % width

            key: str = f"{clue_num}{suffix}"
            entries[key] = (clue_text, answer, (row, col), length)

    return entries


def generate_code(entries: EntriesDict, puzzle_date: str) -> str:
    """Generate Python code for the entries dict."""
    lines: list[str] = [
        f'# NYT Crossword — {puzzle_date}',
        f'# Generated by nyt_crossword_fetch.py',
        '',
        'entries: dict[str, Entry] = {',
    ]

    # Sort: across first (numerically), then down (numerically)
    def sort_key(k: str) -> tuple[int, int]:
        num = int(k[:-1])
        direction = 0 if k.endswith("A") else 1
        return (direction, num)

    for key in sorted(entries.keys(), key=sort_key):
        clue_text, answer, (row, col), length = entries[key]
        # Escape any quotes in clue text
        clue_escaped = clue_text.replace('\\', '\\\\').replace('"', '\\"')
        lines.append(
            f'    "{key}": Entry("{key}", "{clue_escaped}", "{answer}", cells, ({row}, {col}), {length}),'
        )

    lines.append('}')
    return '\n'.join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Fetch NYT crossword and output Entry initializers.")
    parser.add_argument("--cookie", required=True, help="Your NYT-S cookie value")
    parser.add_argument("--date", default=str(date.today()), help="Puzzle date YYYY-MM-DD (default: today)")
    parser.add_argument("--output", default=None, help="Output file path (default: print to stdout)")
    parser.add_argument("--json", action="store_true", help="Also save raw puzzle JSON alongside output file")
    args = parser.parse_args()

    print(f"Fetching NYT crossword for {args.date}...", file=sys.stderr)
    data = fetch_puzzle(args.date, args.cookie)

    print("Parsing puzzle...", file=sys.stderr)
    entries = parse_puzzle(data)

    across_count = sum(1 for k in entries if k.endswith("A"))
    down_count = sum(1 for k in entries if k.endswith("D"))
    print(f"Found {across_count} across and {down_count} down clues.", file=sys.stderr)

    code = generate_code(entries, args.date)

    if args.output:
        with open(args.output, "w") as f:
            f.write(code + "\n")
        print(f"Written to {args.output}", file=sys.stderr)

        if args.json:
            json_path = args.output.replace(".py", "_raw.json")
            with open(json_path, "w") as f:
                json.dump(data, f, indent=2)
            print(f"Raw JSON saved to {json_path}", file=sys.stderr)
    else:
        print(code)


if __name__ == "__main__":
    main()