#!/usr/bin/env python3
"""
NYT Crossword Fetcher
Fetches today's (or any date's) NYT crossword puzzle and outputs
Python Entry initializer code ready to paste into your solver.

Usage:
    python nyt_crossword_fetch.py
    python nyt_crossword_fetch.py --date 2026-03-10
    python nyt_crossword_fetch.py --date 2026-03-10 --output puzzle.py

Cookie setup:
    Create a .env file in the base project directory containing:
        NYT_S_COOKIE=your_cookie_value_here

    How to find your NYT-S cookie value:
    1. Open browser DevTools (F12) while on the NYT crossword page
    2. Go to the Network tab and click any .json request
    3. In the Request Headers, find the Cookie field
    4. Copy the value of NYT-S=... (just the value, not "NYT-S=")
"""

import argparse
import json
import os
import sys
from datetime import date
from typing import Any
import requests
from dotenv import load_dotenv

# Type aliases
PuzzleData = dict[str, Any]
CellData = dict[str, Any]
ClueEntry = tuple[str, str, tuple[int, int], int]  # (clue_text, answer, (row, col), length)
EntriesDict = dict[str, ClueEntry]
ParseResult = tuple[EntriesDict, int, int]  # (entries, rows, cols)


def fetch_puzzle(date_str: str, nyt_s_cookie: str) -> PuzzleData:
    """Fetch the puzzle JSON from the NYT API."""
    url = f"https://www.nytimes.com/svc/crosswords/v6/puzzle/daily/{date_str}.json"
    response = requests.get(
        url,
        headers={
            "Cookie": f"NYT-S={nyt_s_cookie};",
            "Accept": "application/json",
        }
    )
    if response.status_code == 401:
        print("Error: Authentication failed. Check your NYT-S cookie.", file=sys.stderr)
        sys.exit(1)
    if response.status_code != 200:
        print(f"Error: HTTP {response.status_code} fetching puzzle.", file=sys.stderr)
        sys.exit(1)
    return response.json()  # type: ignore[no-any-return]


def parse_puzzle(data: PuzzleData) -> ParseResult:
    """
    Parse NYT puzzle JSON into a dict of Entry constructor args plus grid dimensions.

    The v6 API body[0] contains:
      - cells: flat list of cell dicts, left-to-right, top-to-bottom
          Each cell has: 'answer' (letter or '.'), 'clues' ([across_id, down_id] ints or absent)
      - clues: {'across': [...], 'down': [...]}
          Each clue: {'cells': [cell_indices], 'clueNum': int, 'text': {'plain': str}}
      - dimensions: {'width': int, 'height': int}

    Returns (entries, rows, cols) where entries maps clue key (e.g. "1A") -> (clue_text, answer, (row, col), length)
    """
    body: dict[str, Any] = data["body"][0]
    cells: list[CellData] = body["cells"]
    clue_data: list[dict[str, Any]] = body["clues"]
    width: int = body["dimensions"]["width"]
    height: int = body["dimensions"]["height"]

    entries: EntriesDict = {}

    direction_suffix: dict[str, str] = {"Across": "A", "Down": "D"}

    for clue in clue_data:
        suffix: str = direction_suffix[clue["direction"]]
        clue_num: int = int(clue["label"])
        clue_text_raw: list[dict[str, Any]] | dict[str, Any] = clue["text"]
        clue_text: str = clue_text_raw[0]["plain"] if isinstance(clue_text_raw, list) else clue_text_raw["plain"]
        cell_indices: list[int] = clue["cells"]

        # Derive answer from cell letters
        answer: str = "".join(
            cells[i].get("answer", "?") for i in cell_indices
        )
        # Replace block cells just in case
        answer = answer.replace(".", "?")

        length: int = len(cell_indices)

        # Start position: first cell index -> (row, col)
        first_idx: int = cell_indices[0]
        row: int = first_idx // width
        col: int = first_idx % width

        key: str = f"{clue_num}{suffix}"
        entries[key] = (clue_text, answer, (row, col), length)

    return entries, height, width


def generate_code(entries: EntriesDict, puzzle_date: str, rows: int, cols: int) -> str:
    """Generate a complete puzzle module with header, entries dict, and footer."""
    puzzle_date_obj: date = date.fromisoformat(puzzle_date)
    day_of_week: str = puzzle_date_obj.strftime("%A")
    date_tag: str = puzzle_date.replace("-", "_")
    puzzle_name: str = f"nyt_{date_tag}_{rows}x{cols}"
    title: str = f"NYT {day_of_week} puzzle {puzzle_date} ({rows}x{cols})"

    lines: list[str] = [
        f'# NYT Crossword — {puzzle_date}',
        f'# Generated by nyt_crossword_fetch.py',
        '',
        'from __future__ import annotations',
        'from model import Cell, Entry, Grid',
        'from .registry import register_puzzle',
        '',
        'def create_grid() -> Grid:',
        f'    cells = [[Cell(row=r, col=c) for c in range({cols})] for r in range({rows})]',
        '',
        '    entries: dict[str, Entry] = {',
    ]

    # Sort: across first (numerically), then down (numerically)
    def sort_key(k: str) -> tuple[int, int]:
        num = int(k[:-1])
        direction = 0 if k.endswith("A") else 1
        return (direction, num)

    for key in sorted(entries.keys(), key=sort_key):
        clue_text, answer, (row, col), length = entries[key]
        clue_escaped = clue_text.replace('\\', '\\\\').replace('"', '\\"')
        lines.append(
            f'        "{key}": Entry("{key}", "{clue_escaped}", "{answer}", cells, ({row}, {col}), {length}),'
        )

    lines += [
        '    }',
        '',
        '    # Create the Grid object',
        '    grid = Grid(entries)',
        '    return grid',
        '',
        f'register_puzzle("{puzzle_name}", create_grid, title="{title}", default=True)',
    ]

    return '\n'.join(lines)


def main() -> None:
    load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), "..", "..", "..", ".env"))
    nyt_s_cookie: str | None = os.getenv("NYT_S_COOKIE")
    if not nyt_s_cookie:
        print("Error: NYT_S_COOKIE not found. Add it to a .env file:\n  NYT_S_COOKIE=your_cookie_value_here", file=sys.stderr)
        sys.exit(1)

    parser = argparse.ArgumentParser(description="Fetch NYT crossword and output Entry initializers.")
    parser.add_argument("--date", default=str(date.today()), help="Puzzle date YYYY-MM-DD (default: today)")
    parser.add_argument("--output", default=None, help="Output file path (default: nyt_YYYY_MM_DD_RxC.py)")
    parser.add_argument("--json", action="store_true", help="Also save raw puzzle JSON alongside output file")
    args = parser.parse_args()

    print(f"Fetching NYT crossword for {args.date}...", file=sys.stderr)
    data = fetch_puzzle(args.date, nyt_s_cookie)

    print("Parsing puzzle...", file=sys.stderr)
    entries, rows, cols = parse_puzzle(data)

    across_count = sum(1 for k in entries if k.endswith("A"))
    down_count = sum(1 for k in entries if k.endswith("D"))
    print(f"Found {across_count} across and {down_count} down clues.", file=sys.stderr)

    date_tag: str = args.date.replace("-", "_")
    default_filename: str = f"nyt_{date_tag}_{rows}x{cols}.py"
    output_path: str = args.output if args.output else default_filename

    code = generate_code(entries, args.date, rows, cols)

    with open(output_path, "w") as f:
        f.write(code + "\n")
    print(f"Written to {output_path}", file=sys.stderr)

    if args.json:
        json_path = output_path.replace(".py", "_raw.json")
        with open(json_path, "w") as f:
            json.dump(data, f, indent=2)
        print(f"Raw JSON saved to {json_path}", file=sys.stderr)


if __name__ == "__main__":
    main()