# NYT Crossword — 2026-07-03
# Generated by nyt_crossword_fetch.py

from __future__ import annotations
from model import Cell, Entry, Grid
from .registry import register_puzzle

def create_grid() -> Grid:
    cells = [[Cell(row=r, col=c) for c in range(15)] for r in range(15)]

    entries: dict[str, Entry] = {
        "1A": Entry("1A", "Bank of China Tower architect", "IMPEI", cells, (0, 0), 5),
        "6A": Entry("6A", "Accepts accolades onstage, say", "TAKESABOW", cells, (0, 6), 9),
        "15A": Entry("15A", "Loses some hair, e.g.", "MOLTS", cells, (1, 0), 5),
        "16A": Entry("16A", "Facial feature also known as a \"nasolabial fold\"", "SMILELINE", cells, (1, 6), 9),
        "17A": Entry("17A", "Race to the top", "PRESIDENTIALRUN", cells, (2, 0), 15),
        "19A": Entry("19A", "N.H.L.'s Mammoth, on sports tickers", "UTA", cells, (3, 0), 3),
        "20A": Entry("20A", "Bag that may contain swag", "TOTE", cells, (3, 4), 4),
        "21A": Entry("21A", "In the thick of", "AMIDST", cells, (3, 9), 6),
        "22A": Entry("22A", "Bring on board", "LADE", cells, (4, 0), 4),
        "24A": Entry("24A", "N.A.A.C.P. member?: Abbr.", "ASSN", cells, (4, 5), 4),
        "26A": Entry("26A", "Disingenuous reply to \"Are you asleep?\"", "YES", cells, (4, 10), 3),
        "27A": Entry("27A", "\"omg rly?!\"", "SRSLY", cells, (5, 0), 5),
        "29A": Entry("29A", "They may change midflight, in brief", "ETAS", cells, (5, 6), 4),
        "31A": Entry("31A", "Lays out some green for", "SODS", cells, (5, 11), 4),
        "34A": Entry("34A", "Makes a return that hits the net?", "EFILES", cells, (6, 0), 6),
        "36A": Entry("36A", "Blabs", "YAPS", cells, (6, 7), 4),
        "38A": Entry("38A", "Opposite side", "FOE", cells, (6, 12), 3),
        "39A": Entry("39A", "Saints' setting, with \"the\"", "BIGEASY", cells, (7, 0), 7),
        "41A": Entry("41A", "Congestion easer", "NETIPOT", cells, (7, 8), 7),
        "43A": Entry("43A", "Coffee spot", "URN", cells, (8, 0), 3),
        "44A": Entry("44A", "Huff", "SNIT", cells, (8, 4), 4),
        "46A": Entry("46A", "Fake news", "CANARD", cells, (8, 9), 6),
        "47A": Entry("47A", "Best Actress Oscar winner between Chastain and Stone", "YEOH", cells, (9, 0), 4),
        "49A": Entry("49A", "Gush", "SPEW", cells, (9, 5), 4),
        "51A": Entry("51A", "Pang", "THROE", cells, (9, 10), 5),
        "52A": Entry("52A", "Part of a volcano", "RIM", cells, (10, 2), 3),
        "54A": Entry("54A", "Environmental portmanteau", "SMOG", cells, (10, 6), 4),
        "56A": Entry("56A", "Greets, in a way", "DAPS", cells, (10, 11), 4),
        "57A": Entry("57A", "Prominent feature of Jafar and the Genie in \"Aladdin\"", "GOATEE", cells, (11, 0), 6),
        "60A": Entry("60A", "Villanelle, e.g.", "POEM", cells, (11, 7), 4),
        "62A": Entry("62A", "Advocatus ___", "DEI", cells, (11, 12), 3),
        "63A": Entry("63A", "\"Tell me about it!\"", "IKNOWTHEFEELING", cells, (12, 0), 15),
        "66A": Entry("66A", "Lifestyle for those who go both ways", "BICULTURE", cells, (13, 0), 9),
        "67A": Entry("67A", "Senator Jacky of Nevada", "ROSEN", cells, (13, 10), 5),
        "68A": Entry("68A", "Root crop product", "BEETSUGAR", cells, (14, 0), 9),
        "69A": Entry("69A", "Classic pitchers", "EWERS", cells, (14, 10), 5),
        "1D": Entry("1D", "Item that's not on the list, say", "IMPULSEBUY", cells, (0, 0), 10),
        "2D": Entry("2D", "Shelling", "MORTARFIRE", cells, (0, 1), 10),
        "3D": Entry("3D", "Claims not to have known", "PLEADSIGNORANCE", cells, (0, 2), 15),
        "4D": Entry("4D", "Many sci-fi villains, informally", "ETS", cells, (0, 3), 3),
        "5D": Entry("5D", "\"Really?\"", "ISIT", cells, (0, 4), 4),
        "6D": Entry("6D", "Creature that transmits sleeping sickness", "TSETSE", cells, (0, 6), 6),
        "7D": Entry("7D", "Get-out-of-jail-free card, so to speak", "AMNESTY", cells, (0, 7), 7),
        "8D": Entry("8D", "Nurse's tote", "KIT", cells, (0, 8), 3),
        "9D": Entry("9D", "Essayist who wrote \"Not many sounds in life, and I include all urban and all rural sounds, exceed in interest a knock at the door\"", "ELIA", cells, (0, 9), 4),
        "10D": Entry("10D", "Not looking reputable", "SEAMY", cells, (0, 10), 5),
        "11D": Entry("11D", "Supporters of L.G.B.T.Q.+ people", "ALLIES", cells, (0, 11), 6),
        "12D": Entry("12D", "Tropical specimens that can be either flora or fauna", "BIRDSOFPARADISE", cells, (0, 12), 15),
        "13D": Entry("13D", "Burden", "ONUS", cells, (0, 13), 4),
        "14D": Entry("14D", "Elapsed", "WENT", cells, (0, 14), 4),
        "18D": Entry("18D", "Like a nonstarter, for short", "DOA", cells, (2, 5), 3),
        "23D": Entry("23D", "Woods seen on Broadway", "ELLE", cells, (4, 3), 4),
        "25D": Entry("25D", "Curry accompaniment", "NAAN", cells, (4, 8), 4),
        "28D": Entry("28D", "Pros in Washington", "YEAS", cells, (5, 4), 4),
        "30D": Entry("30D", "What some articles are written on", "SPEC", cells, (5, 9), 4),
        "32D": Entry("32D", "Device in many a garage", "DOOROPENER", cells, (5, 13), 10),
        "33D": Entry("33D", "Play pieces?", "SETDESIGNS", cells, (5, 14), 10),
        "35D": Entry("35D", "Former Medicare IDs", "SSNS", cells, (6, 5), 4),
        "37D": Entry("37D", "Mode, for one", "STAT", cells, (6, 10), 4),
        "40D": Entry("40D", "Choking cause, with \"the\"", "YIPS", cells, (7, 6), 4),
        "42D": Entry("42D", "Very clear, as a telecast", "INHD", cells, (7, 11), 4),
        "45D": Entry("45D", "Oil alternative", "TEMPERA", cells, (8, 7), 7),
        "48D": Entry("48D", "Strongly criticize, with \"at\"", "HITOUT", cells, (9, 3), 6),
        "50D": Entry("50D", "Bass player", "WOOFER", cells, (9, 8), 6),
        "53D": Entry("53D", "Whimpers like a baby ", "MEWLS", cells, (10, 4), 5),
        "55D": Entry("55D", "\"Who knew?!\"", "GEE", cells, (10, 9), 3),
        "57D": Entry("57D", "Brothers ___ (pop stars of the 1960s-80s)", "GIBB", cells, (11, 0), 4),
        "58D": Entry("58D", "Many a classic Steinbeck character", "OKIE", cells, (11, 1), 4),
        "59D": Entry("59D", "Dramatic \"Not you, too?\"", "ETTU", cells, (11, 5), 4),
        "61D": Entry("61D", "Nothing but", "MERE", cells, (11, 10), 4),
        "64D": Entry("64D", "Hold close", "HUG", cells, (12, 6), 3),
        "65D": Entry("65D", "Bass or base", "LOW", cells, (12, 11), 3),
    }

    # Create the Grid object
    grid = Grid(entries)
    return grid

register_puzzle("nyt_2026_07_03_15x15", create_grid, title="NYT Friday puzzle 2026-07-03 (15x15)", default=True)
