# NYT Crossword — 2026-02-24
# Generated by nyt_crossword_fetch.py

from __future__ import annotations
from model import Cell, Entry, Grid
from .registry import register_puzzle

def create_grid() -> Grid:
    cells = [[Cell(row=r, col=c) for c in range(15)] for r in range(15)]

    entries: dict[str, Entry] = {
        "1A": Entry("1A", "Utter rubbish", "DRECK", cells, (0, 0), 5),
        "6A": Entry("6A", "Yellowish color for old computer graphics", "AMBER", cells, (0, 6), 5),
        "11A": Entry("11A", "Showing a smirk, say", "WRY", cells, (0, 12), 3),
        "14A": Entry("14A", "\"Make that two!\"", "METOO", cells, (1, 0), 5),
        "15A": Entry("15A", "Actress Watts of \"The Friend\"", "NAOMI", cells, (1, 6), 5),
        "16A": Entry("16A", "Half of a giggle", "HEE", cells, (1, 12), 3),
        "17A": Entry("17A", "Nuyoricans, e.g.", "ETHNICGROUP", cells, (2, 0), 11),
        "19A": Entry("19A", "Doc who's seen for sinusitis", "ENT", cells, (2, 12), 3),
        "20A": Entry("20A", "Went on the fritz", "DIED", cells, (3, 0), 4),
        "21A": Entry("21A", "Grand project begun by the London Philological Society, in brief", "OED", cells, (3, 5), 3),
        "22A": Entry("22A", "Snowman in \"Frozen\"", "OLAF", cells, (3, 10), 4),
        "24A": Entry("24A", "Fender Stratocaster, e.g.", "ELECTRICGUITAR", cells, (4, 1), 14),
        "29A": Entry("29A", "Its base unit is the kilogram", "MASS", cells, (5, 3), 4),
        "30A": Entry("30A", "Self-written life story, informally", "AUTOBIO", cells, (5, 8), 7),
        "31A": Entry("31A", "Deer ___ (road sign)", "XING", cells, (6, 1), 4),
        "33A": Entry("33A", "Otherwise called, in brief", "AKA", cells, (6, 7), 3),
        "34A": Entry("34A", "Brand of squishy balls", "NERF", cells, (6, 11), 4),
        "35A": Entry("35A", "Involuntary movement", "TIC", cells, (7, 0), 3),
        "36A": Entry("36A", "\"The Disrobing of Christ,\" e.g.", "ELGRECO", cells, (7, 4), 7),
        "40A": Entry("40A", "Fish in some onigiri", "EEL", cells, (7, 12), 3),
        "41A": Entry("41A", "One way to leave a door", "AJAR", cells, (8, 0), 4),
        "43A": Entry("43A", "Asset for a thrower", "AIM", cells, (8, 5), 3),
        "44A": Entry("44A", "Old tape players", "VCRS", cells, (8, 10), 4),
        "46A": Entry("46A", "Tiny swine", "MINIPIG", cells, (9, 0), 7),
        "48A": Entry("48A", "One of the matriarchs in Judaism", "LEAH", cells, (9, 8), 4),
        "50A": Entry("50A", "Thyroid, e.g.", "ENDOCRINEGLAND", cells, (10, 0), 14),
        "54A": Entry("54A", "Oft-discarded part of an orange", "PITH", cells, (11, 1), 4),
        "55A": Entry("55A", "Some reproductive cells", "OVA", cells, (11, 7), 3),
        "56A": Entry("56A", "Baby ones are joeys, familiarly", "ROOS", cells, (11, 11), 4),
        "58A": Entry("58A", "Sprightly dance", "JIG", cells, (12, 0), 3),
        "59A": Entry("59A", "Dress for a soirée, e.g.", "EVENINGGOWN", cells, (12, 4), 11),
        "63A": Entry("63A", "Prefix with sex or brow", "UNI", cells, (13, 0), 3),
        "64A": Entry("64A", "Protection against flooding", "LEVEE", cells, (13, 4), 5),
        "65A": Entry("65A", "Group of smarties", "MENSA", cells, (13, 10), 5),
        "66A": Entry("66A", "\"___ Pepper's Lonely Hearts Club Band\"", "SGT", cells, (14, 0), 3),
        "67A": Entry("67A", "Coffeehouse chain that owns the domain coffee.com", "PEETS", cells, (14, 4), 5),
        "68A": Entry("68A", "Inch (up)", "CREEP", cells, (14, 10), 5),
        "1D": Entry("1D", "Contacted quickly online, informally", "DMED", cells, (0, 0), 4),
        "2D": Entry("2D", "Fix, as shoelaces", "RETIE", cells, (0, 1), 5),
        "3D": Entry("3D", "Blues legend Waters", "ETHEL", cells, (0, 2), 5),
        "4D": Entry("4D", "Formally denounce", "CONDEMN", cells, (0, 3), 7),
        "5D": Entry("5D", "Carp in a Japanese pond", "KOI", cells, (0, 4), 3),
        "6D": Entry("6D", "Brings to a boil?", "ANGERS", cells, (0, 6), 6),
        "7D": Entry("7D", "___ Gras", "MARDI", cells, (0, 7), 5),
        "8D": Entry("8D", "Honeybun", "BOO", cells, (0, 8), 3),
        "9D": Entry("9D", "LiMu ___ (insurance bird)", "EMU", cells, (0, 9), 3),
        "10D": Entry("10D", "Remove, as a page of a notebook", "RIPOUT", cells, (0, 10), 6),
        "11D": Entry("11D", "Brew that's often a little cloudy and fruity", "WHEATBEER", cells, (0, 12), 9),
        "12D": Entry("12D", "Festivals often featuring jousting knights, for short", "RENFAIRES", cells, (0, 13), 9),
        "13D": Entry("13D", "Nevertheless", "YET", cells, (0, 14), 3),
        "18D": Entry("18D", "Beds that might have wheels", "COTS", cells, (2, 5), 4),
        "23D": Entry("23D", "Either bronze animal in front of the Art Institute of Chicago", "LION", cells, (3, 11), 4),
        "25D": Entry("25D", "Word after rib or batting", "CAGE", cells, (4, 4), 4),
        "26D": Entry("26D", "Centerpiece of a birthday celebration", "CAKE", cells, (4, 8), 4),
        "27D": Entry("27D", "Green dip, slangily", "GUAC", cells, (4, 9), 4),
        "28D": Entry("28D", "[Hi-lar-ious!]", "ROFL", cells, (4, 14), 4),
        "31D": Entry("31D", "President of China beginning in 2013", "XIJINPING", cells, (6, 1), 9),
        "32D": Entry("32D", "\"This is pretty cool!\"", "ICANDIGIT", cells, (6, 2), 9),
        "33D": Entry("33D", "Asset for a thrower", "ARM", cells, (6, 7), 3),
        "35D": Entry("35D", "Make friendly to humans", "TAME", cells, (7, 0), 4),
        "37D": Entry("37D", "Hideout", "LAIR", cells, (7, 5), 4),
        "38D": Entry("38D", "Supermodel Hadid", "GIGI", cells, (7, 6), 4),
        "39D": Entry("39D", "Avocado-shaped", "OVAL", cells, (7, 10), 4),
        "42D": Entry("42D", "Civil disturbance", "RIOT", cells, (8, 3), 4),
        "45D": Entry("45D", "Juice box?", "CHARGER", cells, (8, 11), 7),
        "47D": Entry("47D", "I.T. pro's offering", "PCHELP", cells, (9, 4), 6),
        "48D": Entry("48D", "Imposes, as a tax", "LEVIES", cells, (9, 8), 6),
        "49D": Entry("49D", "Jennifer who wrote \"A Visit From the Goon Squad\"", "EGAN", cells, (9, 9), 4),
        "51D": Entry("51D", "Pretty large jazz combo", "NONET", cells, (10, 7), 5),
        "52D": Entry("52D", "Whom a diary is often shown to", "NOONE", cells, (10, 12), 5),
        "53D": Entry("53D", "Search for groundwater, in a way", "DOWSE", cells, (10, 13), 5),
        "57D": Entry("57D", "Jacket closer", "SNAP", cells, (11, 14), 4),
        "58D": Entry("58D", "Au ___ (how roast beef may be served)", "JUS", cells, (12, 0), 3),
        "60D": Entry("60D", "Shape for flying geese", "VEE", cells, (12, 5), 3),
        "61D": Entry("61D", "Apple taster in Eden", "EVE", cells, (12, 6), 3),
        "62D": Entry("62D", "Car brand with the Hummer E.V.", "GMC", cells, (12, 10), 3),
    }

    # Create the Grid object
    grid = Grid(entries)
    return grid

register_puzzle("nyt_2026_02_24_15x15", create_grid, title="NYT Tuesday puzzle 2026-02-24 (15x15)", default=True)
